routes/web.php
<?php
use Illuminate\Support\Facades\Route;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();
Route::get('/', function () {
    return view('auth.login');
});
Route::post('post-login', [App\Http\Controllers\UsersController::class, 'postLogin'])->name('login.post');
Route::post('register', [App\Http\Controllers\UsersController::class, 'register'])->name('employees_register');

Route::group(['middleware'=>['auth']],function(){
    Route::get('/home', [App\Http\Controllers\UsersController::class, 'index'])->name('home');
    Route::get('/profile', [App\Http\Controllers\UsersController::class, 'profile'])->name('profile');
    Route::post('/profile/{id}', [App\Http\Controllers\UsersController::class, 'profileUpdate'])->name('profile-update');
    Route::resource('leaves', App\Http\Controllers\LeaveController::class);
    Route::get('/notificationList', [App\Http\Controllers\UsersController::class, 'notificationList'])->name('notificationList');
});

Route::group(['middleware'=>['auth','admin']],function(){
    Route::resource('employees', App\Http\Controllers\UsersController::class);
});

app/Models/Leave.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Leave extends Model
{
    use HasFactory;
    
    protected $table =  'leaves';
    protected $fillable = [
        'start_date',
        'end_date',
        'reson',
        'user_id',
        'reason',
        'status'
    ];
}

app/Http/Controllers/LeaveController.php
<?php

namespace App\Http\Controllers;

use App\Models\Leave;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use App\Models\User;
use App\Models\Notification;
use Illuminate\Support\Facades\Mail;
class LeaveController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if(Auth()->user()->role == 1){
            $leaves=Leave::orderBy('id','DESC')->paginate(10);
        }else{
            $leaves=Leave::where('user_id',Auth()->user()->id)->orderBy('id','DESC')->paginate(10);
        }
        return view('leaves.index')->with('leaves',$leaves);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('leaves.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $userId = Auth::User()->id;
        
        $adminUserID = User::where('role',1)->pluck('id')->first();
        $userName = Auth()->user()->name;
        $this->validate($request,
        [
            'start_date'=>'required',
            'end_date' => 'required|date|after_or_equal:start_date',
            'reason'=>'required',
        ]);
        // dd($request->all());
        $data=$request->all();
        $data['user_id']= isset($request->user_id) ? $request->user_id : $userId;
        // dd($data);
        $status=Leave::create($data);
        // dd($status);
        if($status){
            $notificationData = [
                'user_id' => $adminUserID,
                'data' => $userName." Applying for leave start date:".$request->start_date." To End Date:".$request->end_date.".",
            ];
            Notification::create($notificationData);

            //mail data to employee for leave status start code
            $user_name = '';
            $user_email = '';
            $user_data = User::select('name','email')->where('id',$userId)->first();
            $user_name = $user_data['name'];
            $data = [
                'email'   => $value = env('ADMIN_EMAIL'),
                'subject' => "Leave: ".$user_name." is apply for leave",
                'body'    =>  "Hello <b>Admin,</b><br><b>".$user_name."</b> is apply for leave start date:<b>".$request->start_date."</b> To End Date:<b>".$request->end_date.".</b>",
            ];

            LeaveController::sentMail($data);
            //mail data to employee for leave status end code
            request()->session()->flash('success','Successfully added leave');
        }
        else{
            request()->session()->flash('error','Error occurred while adding leave');
        }
        return redirect()->route('leaves.index');

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $leave=Leave::findOrFail($id);
        return view('leaves.edit')->with('leave',$leave);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request,
        [
            'start_date'=>'required',
            'end_date' => 'required|date|after_or_equal:start_date',
            'reason'=>'required',
        ]);
       
        $leave=Leave::findOrFail($id);
         
        
        $data=$request->all();
        // dd($data);
        
        $status=$leave->fill($data)->save();
        if($status){
            if (Auth::user() &&  Auth::user()->role == 1) {
                //mail data to employee for leave status start code
                $user_name = '';
                $user_email = '';
                $user_data = User::select('name','email')->where('id',$leave->user_id)->first();
                $user_name = $user_data['name'];
                $user_email = $user_data['email'];
                if($leave->status == 'approved'){
                    $status = 'Approved';
                }else{
                    $status = 'Unapproved';
                }
                $data = [
                    'email'   => $user_email,
                    'subject' => "Leave:Your Leave is ".$status,
                    'body'    =>  "Hello <b>".$user_name.",</b><br> Your Leave is <b>".$status."</b>  for start date:<b>".$leave->start_date."</b> To End Date:<b>".$leave->end_date.".</b>",
                ];

                LeaveController::sentMail($data);
                $notificationData = [
                    'user_id' => $leave->user_id,
                    'data' => "Your leave is ".$status." for start date:".$leave->start_date." To End Date:".$leave->end_date.".",
                ];
                Notification::create($notificationData);
                //mail data to employee for leave status end code
            }
            request()->session()->flash('success','Successfully updated');
        }
        else{
            request()->session()->flash('error','Error occured while updating');
        }
        return redirect()->route('leaves.index');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $delete=Leave::findorFail($id);
        $status=$delete->delete();
        if($status){
            request()->session()->flash('success','Leave Successfully deleted');
        }
        else{
            request()->session()->flash('error','There is an error while deleting leave');
        }
        return redirect()->route('leaves.index');
    }
    public function sentMail($data){
      return $sentmail = Mail::send([], $data, function($message) use ($data)
        {
            $message->to($data['email'])
                    ->subject($data['subject']) 
                    ->setBody($data['body'], 'text/html');
        });
    }
    
}

resources/views/leaves/create.blade.php
@extends('layouts.master')

@section('main-content')

<div class="card">
    <h5 class="card-header">Add Leave</h5>
    <div class="card-body">
      <form method="post" action="{{route('leaves.store')}}">
        {{csrf_field()}}
        <div class="form-group">
          <label for="inputTitle" class="col-form-label">Start Date</label>
        <input id="start_date" type="date" name="start_date" min="{{date('Y-m-d')}}" placeholder="Enter Start Date"  value="{{old('start_date')}}" class="form-control">
        @error('start_date')
        <span class="text-danger">{{$message}}</span>
        @enderror
        </div>
        <div class="form-group">
            <label for="inputEmail" class="col-form-label">End Date</label>
          <input id="end_date" type="date" name="end_date" min="{{date('Y-m-d')}}" placeholder="Enter End Date"  value="{{old('end_date')}}" class="form-control">
          @error('end_date')
          <span class="text-danger">{{$message}}</span>
          @enderror
        </div>

        <div class="form-group">
            <label for="inputPassword" class="col-form-label">Reason</label>
            <textarea id="reason" name="reason" placeholder="Enter Reason"  value="{{old('reason')}}" class="form-control"></textarea>
          @error('reason')
          <span class="text-danger">{{$message}}</span>
          @enderror
        </div>
          <!-- <div class="form-group">
            <label for="status" class="col-form-label">Status</label>
            <select name="status" class="form-control">
                <option value="approved">Approved</option>
                <option value="unapproved">Unapproved</option>
            </select>
          @error('status')
          <span class="text-danger">{{$message}}</span>
          @enderror
          </div> -->
        <div class="form-group mb-3">
          <button type="reset" class="btn btn-warning">Reset</button>
           <button class="btn btn-success" type="submit">Submit</button>
        </div>
      </form>
    </div>
</div>

@endsection

@push('scripts')
<script src="/vendor/laravel-filemanager/js/stand-alone-button.js"></script>
<script>
    $('#lfm').filemanager('image');
</script>
@endpush

resources/views/leaves/edit.blade.php
@extends('layouts.master')

@section('main-content')

<div class="card">
    <h5 class="card-header">Edit Leave</h5>
    <div class="card-body">
      <form method="post" action="{{route('leaves.update',$leave->id)}}">
        @csrf 
        @method('PATCH')
        <div class="form-group">
          <label for="inputTitle" class="col-form-label">Start Date</label>
        <input id="inputTitle" type="date" name="start_date" min="{{date('Y-m-d')}}" placeholder="Enter Start Date"  value="{{$leave->start_date}}" class="form-control">
        @error('start_date')
        <span class="text-danger">{{$message}}</span>
        @enderror
        </div>

        <div class="form-group">
          <label for="inputTitle" class="col-form-label">End  Date</label>
        <input id="inputTitle" type="date" name="end_date" min="{{date('Y-m-d')}}" placeholder="Enter End Date"  value="{{$leave->end_date}}" class="form-control">
        @error('end_date')
        <span class="text-danger">{{$message}}</span>
        @enderror
        </div>
        <div class="form-group">
            <label for="inputPassword" class="col-form-label">Reason</label>
            <textarea id="reason" name="reason" placeholder="Enter Reason" class="form-control">{{$leave->reason}}</textarea>
          @error('reason')
          <span class="text-danger">{{$message}}</span>
          @enderror
        </div>
        @if(Auth()->user()->role == 1)
         <div class="form-group">
            <label for="status" class="col-form-label">Status</label>
            <select name="status" class="form-control">
                <option value="approved" {{(($leave->status=='approved') ? 'selected' : '')}}>Approved</option>
                <option value="upnapproved" {{(($leave->status=='unapproved') ? 'selected' : '')}}>Unapproved</option>
            </select>
          @error('status')
          <span class="text-danger">{{$message}}</span>
          @enderror
          </div>
          @endif
        <div class="form-group mb-3">
           <button class="btn btn-success" type="submit">Update</button>
        </div>
      </form>
    </div>
</div>

@endsection

@push('scripts')
<script src="/vendor/laravel-filemanager/js/stand-alone-button.js"></script>
<script>
    $('#lfm').filemanager('image');
</script>
@endpush

resources/views/leaves/index.blade.php
@extends('layouts.master')

@section('main-content')
 <!-- DataTales Example -->
 <div class="card shadow mb-4">
 
 <div class="card-header py-3">
      <h6 class="m-0 font-weight-bold text-primary float-left">{{ ((isset(Auth()->user()->role)) && (Auth()->user()->role == 1))? 'Leave List' :'Add Leave'}}</h6>
      @if(Auth()->user()->role != 1)
      <a href="{{route('leaves.create')}}" class="btn btn-primary btn-sm float-right" data-toggle="tooltip" data-placement="bottom" title="Add Leave"><i class="fas fa-plus"></i> Add Leave</a>
      @endif
    </div>
    <div class="card-body">
      <div class="table-responsive">
        <table class="table table-bordered" id="user-dataTable" width="100%" cellspacing="0">
          <thead>
            <tr>
              <th>S.N.</th>
              <th>UserName</th>
              <th>StartDate</th>
              <th>EndDate</th>
              <th>Reson</th>
              <th>Status</th>
              <th>Action</th>
            </tr>
          </thead>
          <tfoot>
            <tr>
              <th>S.N.</th>
              <th>UserName</th>
              <th>StartDate</th>
              <th>EndDate</th>
              <th>Reson</th>
              <th>Status</th>
              <th>Action</th>
              </tr>
          </tfoot>
          <tbody>
            @foreach($leaves as $leave)   
            @php 
              $user_name=DB::table('users')->where('id',$leave->user_id)->pluck('name')->first();
              @endphp
                <tr>
                    <td>{{$leave->id}}</td>
                    <td>{{$user_name}}</td>
                    <td>{{ date('d-m-Y', strtotime($leave->start_date)) }}</td>
                    <td>{{ date('d-m-Y', strtotime($leave->end_date))}}</td>
                    <td>{{$leave->reason}}</td>
                    <td>
                        @if($leave->status=='approved')
                            <span class="badge badge-success">{{$leave->status}}</span>
                        @else
                            <span class="badge badge-warning">{{$leave->status}}</span>
                        @endif
                    </td>
                    <td>
                    <a href="{{route('leaves.edit',$leave->id)}}" class="btn btn-primary btn-sm float-left mr-1" style="height:30px; width:30px;border-radius:50%" data-toggle="tooltip" title="edit" data-placement="bottom"><i class="fas fa-edit"></i></a>
                    <form method="POST" action="{{route('leaves.destroy',[$leave->id])}}">
                      @csrf 
                      @method('delete')
                          <button class="btn btn-danger btn-sm dltBtn" data-id={{$leave->id}} style="height:30px; width:30px;border-radius:50%" data-toggle="tooltip" data-placement="bottom" title="Delete"><i class="fas fa-trash-alt"></i></button>
                        </form>
                    </td>
                    {{-- Delete Modal --}}
                    {{-- <div class="modal fade" id="delModal{{$leave->id}}" tabindex="-1" role="dialog" aria-labelledby="#delModal{{$user->id}}Label" aria-hidden="true">
                        <div class="modal-dialog" role="document">
                          <div class="modal-content">
                            <div class="modal-header">
                              <h5 class="modal-title" id="#delModal{{$leave->id}}Label">Delete Leave</h5>
                              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                              </button>
                            </div>
                            <div class="modal-body">
                              <form method="post" action="{{ route('leave.destroy',$leave->id) }}">
                                @csrf 
                                @method('delete')
                                <button type="submit" class="btn btn-danger" style="margin:auto; text-align:center">Parmanent delete user</button>
                              </form>
                            </div>
                          </div>
                        </div>
                    </div> --}}
                </tr>  
            @endforeach
          </tbody>
        </table>
        <span style="float:right">{{$leaves->links()}}</span>
      </div>
    </div>
</div>
@endsection

@push('styles')
  <link href="{{asset('backend/vendor/datatables/dataTables.bootstrap4.min.css')}}" rel="stylesheet">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.min.css" />
  <style>
      div.dataTables_wrapper div.dataTables_paginate{
          display: none;
      }
  </style>
@endpush

@push('scripts')

  <!-- Page level plugins -->
  <script src="{{asset('backend/vendor/datatables/jquery.dataTables.min.js')}}"></script>
  <script src="{{asset('backend/vendor/datatables/dataTables.bootstrap4.min.js')}}"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/2.1.2/sweetalert.min.js"></script>

  <!-- Page level custom scripts -->
  <script src="{{asset('backend/js/demo/datatables-demo.js')}}"></script>
  <script>
      
      $('#user-dataTable').DataTable( {
            "columnDefs":[
                {
                    "orderable":false,
                    "targets":[6]
                }
            ]
        } );

        // Sweet alert

        function deleteData(id){
            
        }
  </script>
  <script>
      $(document).ready(function(){
        $.ajaxSetup({
            headers: {
                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
            }
        });
          $('.dltBtn').click(function(e){
            var form=$(this).closest('form');
              var dataID=$(this).data('id');
              // alert(dataID);
              e.preventDefault();
              swal({
                    title: "Are you sure?",
                    text: "Once deleted, you will not be able to recover this data!",
                    icon: "warning",
                    buttons: true,
                    dangerMode: true,
                })
                .then((willDelete) => {
                    if (willDelete) {
                       form.submit();
                    } else {
                        swal("Your data is safe!");
                    }
                });
          })
      })
  </script>
@endpush

resources/views/leaves/profile.blade.php
@extends('backend.layouts.master')

@section('title','Admin Profile')

@section('main-content')

<div class="card shadow mb-4">
    <div class="row">
        <div class="col-md-12">
           @include('backend.layouts.notification')
        </div>
    </div>
   <div class="card-header py-3">
     <h4 class=" font-weight-bold">Profile</h4>
     <ul class="breadcrumbs">
         <li><a href="{{route('admin')}}" style="color:#999">Dashboard</a></li>
         <li><a href="" class="active text-primary">Profile Page</a></li>
     </ul>
   </div>
   <div class="card-body">
        <div class="row">
            <div class="col-md-4">
                <div class="card">
                    <div class="image">
                        @if($profile->photo)
                        <img class="card-img-top img-fluid roundend-circle mt-4" style="border-radius:50%;height:80px;width:80px;margin:auto;" src="{{$profile->photo}}" alt="profile picture">
                        @else 
                        <img class="card-img-top img-fluid roundend-circle mt-4" style="border-radius:50%;height:80px;width:80px;margin:auto;" src="{{asset('backend/img/avatar.png')}}" alt="profile picture">
                        @endif
                    </div>
                    <div class="card-body mt-4 ml-2">
                      <h5 class="card-title text-left"><small><i class="fas fa-user"></i> {{$profile->name}}</small></h5>
                      <p class="card-text text-left"><small><i class="fas fa-envelope"></i> {{$profile->email}}</small></p>
                      <p class="card-text text-left"><small class="text-muted"><i class="fas fa-hammer"></i> {{$profile->role}}</small></p>
                    </div>
                  </div>
            </div>
            <div class="col-md-8">
                <form class="border px-4 pt-2 pb-3" method="POST" action="{{route('profile-update',$profile->id)}}">
                    @csrf
                    <div class="form-group">
                        <label for="inputTitle" class="col-form-label">Name</label>
                      <input id="inputTitle" type="text" name="name" placeholder="Enter name"  value="{{$profile->name}}" class="form-control">
                      @error('name')
                      <span class="text-danger">{{$message}}</span>
                      @enderror
                      </div>
              
                      <div class="form-group">
                          <label for="inputEmail" class="col-form-label">Email</label>
                        <input id="inputEmail" disabled type="email" name="email" placeholder="Enter email"  value="{{$profile->email}}" class="form-control">
                        @error('email')
                        <span class="text-danger">{{$message}}</span>
                        @enderror
                      </div>
              
                      <div class="form-group">
                      <label for="inputPhoto" class="col-form-label">Photo</label>
                      <div class="input-group">
                          <span class="input-group-btn">
                              <a id="lfm" data-input="thumbnail" data-preview="holder" class="btn btn-primary">
                              <i class="fa fa-picture-o"></i> Choose
                              </a>
                          </span>
                          <input id="thumbnail" class="form-control" type="text" name="photo" value="{{$profile->photo}}">
                      </div>
                        @error('photo')
                        <span class="text-danger">{{$message}}</span>
                        @enderror
                      </div>

                        <button type="submit" class="btn btn-success btn-sm">Update</button>
                </form>
            </div>
        </div>
   </div>
</div>

@endsection

<style>
    .breadcrumbs{
        list-style: none;
    }
    .breadcrumbs li{
        float:left;
        margin-right:10px;
    }
    .breadcrumbs li a:hover{
        text-decoration: none;
    }
    .breadcrumbs li .active{
        color:red;
    }
    .breadcrumbs li+li:before{
      content:"/\00a0";
    }
    .image{
        background:url('{{asset('backend/img/background.jpg')}}');
        height:150px;
        background-position:center;
        background-attachment:cover;
        position: relative;
    }
    .image img{
        position: absolute;
        top:55%;
        left:35%;
        margin-top:30%;
    }
    i{
        font-size: 14px;
        padding-right:8px;
    }
  </style> 

@push('scripts')
<script src="/vendor/laravel-filemanager/js/stand-alone-button.js"></script>
<script>
    $('#lfm').filemanager('image');
</script>
@endpush